baseURL = 'https://kromg.github.io/'
languageCode = 'en-us'
title = "Lost in IT | Kromg"
theme = 'ananke'

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 10 
# Use a low weight to place it near the beginning, e.g., after Home.
